---
# necessary steps to deploy the role.

- name: check if already installed
  stat: path={{ miniconda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: download miniconda installer
  sudo: no
  get_url:
    url={{ miniconda_url }}
    dest=/tmp/miniconda.sh
    mode=0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False

- name: install miniconda
  sudo: no
  shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded | success
  notify:
    - remove miniconda setup script
    - update conda to latest version
